on:
  push:
    branches:
      - main
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip install sphinx
      - run: sphinx-build docs _build
      - uses: actions/upload-artifact@v4
        with:
          name: docs-artifact
          path: _build
          if-no-files-found: error

  build-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ref: main
            name: app-testing
          - ref: v0.1.0
            name: app-stable
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: dist
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: [build-docs, build-app]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-testing
          path: testing
      - uses: actions/download-artifact@v4
        with:
          name: app-stable
          path: stable
      - uses: actions/download-artifact@v4
        with:
          name: docs-artifact
          path: .
      - run: find
      - uses: actions/configure-pages@v1
      - uses: actions/upload-pages-artifact@v1
        with:
           path: .
      - id: deployment
        uses: actions/deploy-pages@v1
